-- colorscheme
Util.pack.load "flexoki"

local ok, flexoki = pcall(require, "flexoki")
if not ok then
  vim.cmd.colorscheme "habamax"
else
  local c = require("flexoki.palette").palette()
  flexoki.setup {
    float_window_style = "border",
    highlight_groups = {
      -- Tree-sitter
      ["@variable"] = { fg = c.tx, italic = false },
      ["@parameter"] = { fg = c["pu-2"], italic = false },
      ["@variable.parameter"] = { fg = c["pu-2"], italic = false },
      ["@variable.member"] = { fg = c["cy-2"] },
      ["@field"] = { fg = c["cy-2"] },
      ["@property"] = { fg = c["cy-2"] },
      ["@module"] = { link = "Include" },
      ["@module.builtin"] = { link = "Include" },
      ["@namespace"] = { link = "Include" },
      ["@symbol"] = { link = "Identifier" },
      ["@boolean"] = { link = "Boolean" },
      ["@number"] = { link = "Number" },
      ["@number.float"] = { link = "Number" },
      ["@float"] = { link = "Number" },
      ["@string.regexp"] = { link = "String" },
      ["@regexp"] = { link = "String" },
      ["@string.special.symbol"] = { link = "Identifier" },
      ["@string.special.url"] = { fg = c["pu-2"], underline = true },
      ["@type"] = { fg = c["cy-2"] },
      ["@type.builtin"] = { fg = c["cy-2"], bold = true },
      ["@class"] = { fg = c["cy-2"] },
      ["@interface"] = { fg = c["cy-2"] },
      ["@attribute.diff"] = { fg = c["or-2"] },
      ["@function.method"] = { fg = c["ma-2"] },
      ["@function.method.call"] = { fg = c["ma-2"] },
      ["@method"] = { fg = c["ma-2"] },
      ["@macro"] = { link = "Macro" },
      ["@function.macro"] = { link = "Macro" },
      ["@include"] = { link = "Include" },
      ["@keyword.import"] = { link = "Include" },
      ["@conditional"] = { link = "Conditional" },
      ["@keyword.conditional"] = { link = "Conditional" },
      ["@repeat"] = { link = "Repeat" },
      ["@keyword.repeat"] = { link = "Repeat" },
      ["@preproc"] = { link = "PreProc" },
      ["@keyword.directive"] = { link = "PreProc" },
      ["@keyword.directive.define"] = { link = "Define" },
      ["@storageclass"] = { link = "StorageClass" },
      ["@keyword.modifier"] = { link = "StorageClass" },
      ["@punctuation"] = { fg = c["tx-3"] },
      ["@punctuation.bracket"] = { link = "@punctuation" },
      ["@punctuation.delimiter"] = { link = "@punctuation" },
      ["@punctuation.special"] = { link = "@punctuation" },
      ["@text"] = { fg = c.tx },
      ["@text.danger"] = { fg = c["re-2"] },
      ["@text.diff.add"] = { fg = c["gr-2"], bg = c["gr-2"], blend = 20 },
      ["@text.diff.delete"] = { fg = c["re-2"], bg = c["re-2"], blend = 20 },
      ["@text.emphasis"] = { italic = false },
      ["@text.environment"] = { link = "Macro" },
      ["@text.environment.name"] = { link = "Type" },
      ["@text.math"] = { link = "Special" },
      ["@text.note"] = { link = "SpecialComment" },
      ["@text.strike"] = { strikethrough = true },
      ["@text.strong"] = { bold = true },
      ["@text.title"] = { link = "Title" },
      ["@text.title.1.markdown"] = { link = "markdownH1" },
      ["@text.title.1.marker.markdown"] = { link = "markdownH1Delimiter" },
      ["@text.title.2.markdown"] = { link = "markdownH2" },
      ["@text.title.2.marker.markdown"] = { link = "markdownH2Delimiter" },
      ["@text.title.3.markdown"] = { link = "markdownH3" },
      ["@text.title.3.marker.markdown"] = { link = "markdownH3Delimiter" },
      ["@text.title.4.markdown"] = { link = "markdownH4" },
      ["@text.title.4.marker.markdown"] = { link = "markdownH4Delimiter" },
      ["@text.title.5.markdown"] = { link = "markdownH5" },
      ["@text.title.5.marker.markdown"] = { link = "markdownH5Delimiter" },
      ["@text.title.6.markdown"] = { link = "markdownH6" },
      ["@text.title.6.marker.markdown"] = { link = "markdownH6Delimiter" },
      ["@text.underline"] = { underline = true },
      ["@text.uri"] = { fg = c["pu-2"], underline = true },
      ["@text.warning"] = { fg = c["or-2"] },
      ["@todo"] = { link = "Todo" },
      ["@comment.error"] = { fg = c["re-2"] },
      ["@comment.warning"] = { fg = c["or-2"] },
      ["@comment.todo"] = { fg = c["ma-2"], bg = c["ma-2"], blend = 20 },
      ["@comment.note"] = { fg = c["bl-2"], bg = c["bl-2"], blend = 20 },
      ["@markup.strong"] = { bold = true },
      ["@markup.italic"] = { italic = false },
      ["@markup.strikethrough"] = { strikethrough = true },
      ["@markup.underline"] = { underline = true },
      ["@markup.heading"] = { fg = c["cy-2"], bold = true },
      ["@markup.heading.1.markdown"] = { link = "markdownH1" },
      ["@markup.heading.1.marker.markdown"] = { link = "markdownH1Delimiter" },
      ["@markup.heading.2.markdown"] = { link = "markdownH2" },
      ["@markup.heading.2.marker.markdown"] = { link = "markdownH2Delimiter" },
      ["@markup.heading.3.markdown"] = { link = "markdownH3" },
      ["@markup.heading.3.marker.markdown"] = { link = "markdownH3Delimiter" },
      ["@markup.heading.4.markdown"] = { link = "markdownH4" },
      ["@markup.heading.4.marker.markdown"] = { link = "markdownH4Delimiter" },
      ["@markup.heading.5.markdown"] = { link = "markdownH5" },
      ["@markup.heading.5.marker.markdown"] = { link = "markdownH5Delimiter" },
      ["@markup.heading.6.markdown"] = { link = "markdownH6" },
      ["@markup.heading.6.marker.markdown"] = { link = "markdownH6Delimiter" },
      ["@markup.quote"] = { fg = c.tx },
      ["@markup.math"] = { link = "Special" },
      ["@markup.environment"] = { link = "Macro" },
      ["@markup.environment.name"] = { link = "@type" },
      ["@markup.link"] = { fg = c["tx-2"] },
      ["@markup.link.label"] = { fg = c["cy-2"] },
      ["@markup.link.markdown_inline"] = { fg = c["tx-2"] },
      ["@markup.link.label.markdown_inline"] = { fg = c["cy-2"] },
      ["@markup.link.url"] = { fg = c["pu-2"], underline = true },
      ["@markup.raw"] = { fg = c["cy-2"] },
      ["@markup.raw.block"] = { fg = c["cy-2"] },
      ["@markup.raw.delimiter.markdown"] = { fg = c["tx-3"] },
      ["@markup.list"] = { fg = c["bl-2"] },
      ["@markup.list.checked"] = { fg = c["cy-2"], bg = c["cy-2"], blend = 10 },
      ["@markup.list.unchecked"] = { fg = c.tx },
      ["@diff.plus"] = { fg = c["gr-2"], bg = c["gr-2"], blend = 20 },
      ["@diff.minus"] = { fg = c["re-2"], bg = c["re-2"], blend = 20 },
      ["@diff.delta"] = { bg = c["ye-2"], blend = 20 },
      ["@tag.attribute"] = { fg = c["pu-2"] },
      ["@tag.delimiter"] = { fg = c["tx-3"] },
      ["@conceal.markdown"] = { fg = c["tx-3"] },
      ["@lsp.type.interface"] = { link = "@interface" },
      ["@lsp.type.namespace"] = { link = "@namespace" },
      ["@lsp.type.parameter"] = { link = "@parameter" },
      ["@lsp.type.property"] = { link = "@property" },
      markdownH1 = { fg = c["pu-2"], bold = true },
      markdownH1Delimiter = { link = "markdownH1" },
      markdownH2 = { fg = c["cy-2"], bold = true },
      markdownH2Delimiter = { link = "markdownH2" },
      markdownH3 = { fg = c["ma-2"], bold = true },
      markdownH3Delimiter = { link = "markdownH3" },
      markdownH4 = { fg = c["or-2"], bold = true },
      markdownH4Delimiter = { link = "markdownH4" },
      markdownH5 = { fg = c["bl-2"], bold = true },
      markdownH5Delimiter = { link = "markdownH5" },
      markdownH6 = { fg = c["gr-2"], bold = true },
      markdownH6Delimiter = { link = "markdownH6" },

      StatusLine = { fg = c.tx, bg = c.ui },
      StatusLineNC = { fg = c["tx-2"], bg = c.ui },
      MsgArea = { fg = c.tx, bg = c.bg },
      MsgSeparator = { fg = c["tx-3"], bg = c.bg },
      ModeMsg = { fg = c.tx, bg = c.bg },
      MoreMsg = { fg = c["pu-2"], bg = c.bg },
      Question = { fg = c["or-2"], bg = c.bg },
      ErrorMsg = { fg = c["re-2"], bg = c.bg },
      WarningMsg = { fg = c["or-2"], bg = c.bg },
      SimpleStatusline = { fg = c.tx, bg = c.ui },
      SimpleStatuslineModeNormal = { fg = c.bg, bg = c["bl-2"], bold = true },
      SimpleStatuslineModeInsert = { fg = c.bg, bg = c["gr-2"], bold = true },
      SimpleStatuslineModeVisual = { fg = c.bg, bg = c["ma-2"], bold = true },
      SimpleStatuslineModeReplace = { fg = c.bg, bg = c["re-2"], bold = true },
      SimpleStatuslineModeCommand = { fg = c.bg, bg = c["ye-2"], bold = true },
      SimpleStatuslineModeOther = { fg = c.bg, bg = c["pu-2"], bold = true },
      SimpleStatuslineAccent = { fg = c["bl-2"], bg = c.ui },
      SimpleStatuslineDebug = { fg = c["or-2"], bg = c.ui },
      SimpleStatuslineWarn = { fg = c["or-2"], bg = c.ui },
      SimpleStatuslineFile = { fg = c.tx, bg = c.ui, bold = true },
      SimpleStatuslineInfo = { fg = c["pu-2"], bg = c.ui },
      SimpleStatuslineLint = { fg = c["gr-2"], bg = c.ui },
      SimpleStatuslineLintRunning = { fg = c["ye-2"], bg = c.ui, bold = true },
      SimpleStatuslineMuted = { fg = c["tx-3"], bg = c.ui },
      SimpleStatuslineLocation = { fg = c["cy-2"], bg = c.ui },
      QuickFixLine = { bg = c["ui-3"] },
      WinBar = { bg = c.bg },
      WinBarNC = { bg = c.bg },
      LspCodeLens = { fg = c["pu-2"], italic = true },
      LspCodeLensSeparator = { fg = c["tx-3"], italic = true },
      DropBarMenuCurrentContext = { bg = c.bg },

      -- grug-far.nvim
      GrugFarHelpHeader = { fg = c["bl-2"] },
      GrugFarHelpHeaderKey = { fg = c["or-2"] },
      GrugFarHelpWinActionKey = { fg = c["or-2"] },
      GrugFarHelpWinActionPrefix = { fg = c["cy-2"] },
      GrugFarHelpWinActionText = { fg = c["bl-2"] },
      GrugFarHelpWinHeader = { link = "FloatTitle" },
      GrugFarInputLabel = { fg = c["cy-2"] },
      GrugFarInputPlaceholder = { link = "Comment" },
      GrugFarResultsActionMessage = { fg = c["cy-2"] },
      GrugFarResultsChangeIndicator = { fg = c["ye-2"] },
      GrugFarResultsHeader = { fg = c["bl-2"] },
      GrugFarResultsLineNo = { fg = c["pu-2"] },
      GrugFarResultsLineColumn = { link = "GrugFarResultsLineNo" },
      GrugFarResultsMatch = { link = "CurSearch" },
      GrugFarResultsPath = { fg = c["cy-2"] },
      GrugFarResultsStats = { fg = c["pu-2"] },

      -- gitsigns.nvim
      GitSignsAdd = { link = "SignAdd" },
      GitSignsChange = { link = "SignChange" },
      GitSignsDelete = { link = "SignDelete" },
      GitSignsAddInline = { fg = c["gr-2"] },
      GitSignsChangeInline = { fg = c["ye-2"] },
      GitSignsDeleteInline = { fg = c["re-2"] },
      SignAdd = { fg = c["gr-2"], bg = "NONE" },
      SignChange = { fg = c["ye-2"], bg = "NONE" },
      SignDelete = { fg = c["re-2"], bg = "NONE" },
    },
  }
  vim.cmd.colorscheme "flexoki"
end
