require("ibl").setup {
  indent = {
    char = "│",
    tab_char = "│",
    priority = 2,
  },
  scope = {
    enabled = true,
    char = "┃",
    show_start = false,
    show_end = false,
    priority = 1000,
    include = {
      node_type = {
        ["*"] = {
          "argument_list",
          "arguments",
          "assignment_statement",
          "Block",
          "chunk",
          "class",
          "ContainerDecl",
          "dictionary",
          "do_block",
          "do_statement",
          "element",
          "except",
          "FnCallArguments",
          "for",
          "for_statement",
          "function",
          "function_declaration",
          "function_definition",
          "if_statement",
          "IfExpr",
          "IfStatement",
          "import",
          "InitList",
          "list_literal",
          "method",
          "object",
          "ParamDeclList",
          "repeat_statement",
          "selector",
          "SwitchExpr",
          "table",
          "table_constructor",
          "try",
          "tuple",
          "type",
          "var",
          "while",
          "while_statement",
          "with",
        },
      },
    },
  },
  exclude = {
    filetypes = {
      "", -- for all buffers without a file type
      "alpha",
      "big_file_disabled_ft",
      "fugitive",
      "git",
      "gitcommit",
      "help",
      "json",
      "log",
      "markdown",
      "neo-tree",
      "Outline",
      "startify",
      "TelescopePrompt",
      "txt",
      "undotree",
      "vimwiki",
      "vista",
    },
    buftypes = { "terminal", "nofile", "quickfix", "prompt" },
  },
}
