return {
  "lewis6991/impatient.nvim",
  "nvim-lua/plenary.nvim",
  "jghauser/mkdir.nvim",
  "nvim-tree/nvim-web-devicons",
  {
    "rose-pine/neovim",
    name = "rose-pine",
    priority = 1000,
    lazy = false,
    opts = {
      disable_italics = true,
      dark_variant = "main",
      highlight_groups = {
        Comment = { fg = "muted", italic = true },
        StatusLine = { fg = "rose", bg = "iris", blend = 10 },
        StatusLineNC = { fg = "subtle", bg = "surface" },
        TelescopeBorder = { fg = "highlight_high" },
        TelescopeNormal = { fg = "subtle" },
        TelescopePromptNormal = { fg = "text" },
        TelescopeSelection = { fg = "text" },
        TelescopeSelectionCaret = { fg = "iris" },
        WindowPickerStatusLine = { fg = "rose", bg = "iris", blend = 10 },
        WindowPickerStatusLineNC = { fg = "subtle", bg = "surface" },
        GlanceWinBarTitle = { fg = "rose", bg = "iris", blend = 10 },
        GlanceWinBarFilepath = { fg = "subtle", bg = "surface" },
        GlanceWinBarFilename = { fg = "love", bg = "surface" },
        GlancePreviewNormal = { fg = "highlight_high" },
        GlancePreviewMatch = { fg = "love" },
        IblScope = { fg = "rose" },
      },
    },
  },
  {
    "max397574/better-escape.nvim",
    event = "InsertEnter",
    opts = { timeout = 200, clear_empty_lines = true, keys = "<Esc>" },
  },
}
